name = "portfolio-maintenance"
main = "index.js"
compatibility_date = "2024-03-05"

# To toggle maintenance mode via code:
# Use the patterns below
# To ENABLE maintenance mode, uncomment the live routes and comment the dev route.
# To DISABLE, do the opposite.

# LIVE ROUTES
[[routes]]
pattern = "lucasshiota.com/*"
[[routes]]
pattern = "*.lucasshiota.com/*"

# DEV/PARKING ROUTE
[[routes]]
# pattern = "dev.lucasshiota.com/*"
