name = "portfolio-maintenance"
main = "index.js"
compatibility_date = "2024-03-05"

# To toggle maintenance mode via code:
# Switch the patterns below to fake subdomains (e.g., dev.lucasshiota.com) to DISABLE.
# Use the patterns below to ENABLE globally.

routes = [
  "dev.lucasshiota.com/*",
  "*.lucasshiota.com/*"
]
